feature/Coffe Machine
Streaker1425/JavaEdNIX pull request #1
Opened 2021-10-31 20:34 UTC by Streaker1425

2021-11-06 14:24 UTC, maxsomochkin requested changes

2021-11-06 14:24 UTC, maxsomochkin commented on src/feature/coffeMachine/CoffeeMachine.java
> +            if(water >= 0 && water <= 50000) break;
Все константы вынеси в отдельный класс, например:
public static final int MIN_CAPUCHINO_WATER = 100;
public static final int MIN_WATER = 0;
и т.д.

if(water >=MIN_WATER && water <=MAX_WATER){
 break;
}

2021-11-06 14:24 UTC, maxsomochkin commented on src/feature/coffeMachine/CoffeeMachine.java
> +            if(milk >= 0 && milk <= 15000) break;
Все операторы с новой строки
и if всегда с фигурными скобками:
if(...){
...
}else{
...
}

Проверь весь код ниже

2021-11-06 14:24 UTC, maxsomochkin commented on src/feature/coffeMachine/CoffeeMachine.java
> +            int code = scan.nextInt();
Более осмысленные названия переменных

2021-11-09 23:39 UTC, asrubel commented on src/feature/coffeMachine/CoffeeMachine.java
> +    Scanner scan = new Scanner(System.in);
лучше его статическим сделай

2021-11-13 17:39 UTC, Streaker1425 commented on src/feature/coffeMachine/CoffeeMachine.java
> +    Scanner scan = new Scanner(System.in);
![image](https://user-images.githubusercontent.com/91281678/141653604-4595bdbb-3e9c-4fd5-9dd3-dc78342b5269.png)
Мне не дает его сделать статическим

2021-11-15 20:56 UTC, MaximSomochkin approved these changes

2021-11-16 16:52 UTC, merged